flexera/flexera-plugins

aws/rs_aws_rds/README.md
aws/rs_aws_rds/aws_rds_plugin.rb
aws/rs_aws_rds/rds_test_cat.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/4)

Rds db subnet group

---

azure/rs_azure_sql/azure_sql_plugin.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/17)

Azure other plugins

---

aws/rs_aws_rds/aws_rds_plugin.rb
aws/rs_aws_rds/changelog.md

Example CloudApp using a string for allocated_storage: https://selfservice-3.rightscale.com/manager/exe/59774a51edf6de00949dcb2c
Example CloudApp using a number for allocated_storage: https://selfservice-3.rightscale.com/manager/exe/59774aa4b614055e61772195

change all fields to strings

---

aws/rs_aws_rds/aws_rds_plugin.rb
aws/rs_aws_rds/changelog.md

evidence: https://selfservice-3.rightscale.com/manager/exe/5977565dedf6de00aa1e7889
https://us-3.rightscale.com/acct/30601/clouds/1/rds_browser?ui_route=instances/my-rds-971128003/info

tweak resource hrefs. fixes #27

---

azure/rs_azure_storage/README.md
azure/rs_azure_storage/azure_storage_plugin.rb
azure/rs_azure_storage/changelog.md
azure/rs_azure_storage/storage_test_cat.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/35)

Azure storage

---

aws/rs_aws_rds/aws_rds_plugin.rb
aws/rs_aws_rds/changelog.md

- add retries to auto-terminate
- remove unnecessary RCL definitions
- remove audit entry logging on termiante

RDS Issue 33

---

azure/rs_azure_compute/README.md
azure/rs_azure_compute/azure_compute_plugin.rb
azure/rs_azure_compute/changelog.md
azure/rs_azure_compute/compute_test_cat.rb

https://selfservice-3.rightscale.com/manager/exe/5980c74967a20837d8250041
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/42)

adding in extensions support, closes #31

---

azure/rs_azure_template/ARM_template_test_CAT.rb
azure/rs_azure_template/changelog.md
azure/rs_azure_template/rs_azure_template.rb

Improved error handling.
Example of successful launch: https://selfservice-3.rightscale.com/manager/exe/598366c94415ac1a2c95324e
Example of successfully catching a status other than "succeeded" and raising an error: https://selfservice-3.rightscale.com/manager/exe/598366934415ac1a2c952f11

Improve Error Handling on ARM Template Plugin

---

azure/rs_azure_compute/README.md
azure/rs_azure_compute/azure_compute_plugin.rb
azure/rs_azure_compute/changelog.md
azure/rs_azure_compute/compute_test_cat.rb

Updated the Azure Compute plugin to support update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/60)

Adding update to the Azure Compute VirtualMachine resource

---

azure/rs_azure_compute/README.md
azure/rs_azure_compute/azure_compute_plugin.rb
azure/rs_azure_compute/changelog.md
azure/rs_azure_compute/compute_test_cat.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/62)

Adding vmSizes() action to VirtualMachine resource

---

aws/rs_aws_rds/aws_rds_plugin.rb
aws/rs_aws_rds/changelog.md

adding in handle retries for #55
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/59)

adding in handle_retries

---

azure/rs_azure_containerservices/README.md
azure/rs_azure_containerservices/azure_containerservices_plugin.rb
azure/rs_azure_containerservices/changelog.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/56)

Azure Container Service adding in update, and delete retry

---

aws/rs_aws_alb/aws_alb_plugin.rb
aws/rs_aws_cft/aws_cft_plugin.rb
aws/rs_aws_cft/changelog.md
aws/rs_aws_efs/aws_efs_plugin.rb
aws/rs_aws_elb/elb_plugin.rb
aws/rs_aws_rds/aws_rds_plugin.rb
google/gce/gce_plugin.rb
google/google_cloud_dns/google_cloud_dns.rb

fixed filter field on CFT plugin & versioned up.
added long_description to ALB, EFS, ELB, GCE, & GCP Cloud DNS plugins.
removed excessive comments from RDS plugin.

AWS CFT - fix "filter" field

---

CODEOWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/66)

Adding CODEOWNERS to git root

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/72)

Changelog Update for 08-21-2017 Release

---

aws/rs_aws_vpc/README.md
aws/rs_aws_vpc/aws_vpc_plugin.rb
aws/rs_aws_vpc/changelog.md
aws/rs_aws_vpc/vpc_plugin_test_cat.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/74)

AWS VPC Plugin - Adding Nat Gateway Support, Addresses Read-Only Support

---

aws/rs_aws_vpc/README.md
aws/rs_aws_vpc/aws_vpc_plugin.rb
aws/rs_aws_vpc/changelog.md
aws/rs_aws_vpc/vpc_plugin_test_cat.rb

https://selfservice-3.rightscale.com/manager/exe/59a5a4f25ad242005229ae9d
https://cl.ly/3a060P3u241U
https://cl.ly/3I0n041N0e3s

AWS VPC Plugin - Adding in Actions: EnableVpcClassicLink,EnableVpcClassicLinkDnsSupport,Create_Tag

---

azure/rs_azure_key_vault/README.md
azure/rs_azure_key_vault/azure_keyvault_plugin.rb
azure/rs_azure_key_vault/changelog.md
azure/rs_azure_key_vault/keyvault_test_cat.rb

https://selfservice-3.rightscale.com/manager/exe/59cd74a496513565275b4690

Azure Key Vault - Initial Release

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/73)

REPO Maintenance: Adding in issue templates

---

CODEOWNERS
CONTRIBUTING.md

1. Adds Tushar to list properly
2. Updates contributing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/92)

REPO Maintenance: Updating contributing.md and Codeowners

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/93)

Release Changelog 10-26-2017

---

CHANGELOG.md

Release 10 26 2017

---

CHANGELOG.md

changeling for 10-30-2017

---

azure/rs_azure_networking/README.md
azure/rs_azure_networking/changelog.md
azure/rs_azure_networking/peering_test_cat.rb
azure/rs_azure_networking/rs_azure_networking_plugin.rb

* Add Azure VNET peering resource
* Update change log and standardize quoting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/101)

Add VNET peering resource (#96)

---

README.md
aws/rs_aws_mq/README.md
aws/rs_aws_mq/aws_mq_plugin.rb
aws/rs_aws_mq/changelog.md
aws/rs_aws_mq/mq_test_cat.rb
aws/rs_aws_vpc/README.md
aws/rs_aws_vpc/aws_vpc_plugin.rb
aws/rs_aws_vpc/changelog.md

- Initial release of AWS MQ Plugin
- Updated AWS VPC Plugin to support AWS PrivateLink
N/A

AWS MQ & AWS PrivateLink - Initial Releases 

---

aws/rs_aws_lambda/README.md

Lambda README update.  Add link to lambda-optima-markups repo
N/A

Add Complex Lambda Plugin Example

---

azure/rs_azure_networking/README.md
azure/rs_azure_networking/changelog.md
azure/rs_azure_networking/lb_test_cat.rb
azure/rs_azure_networking/nsg_to_subnet_test_cat.rb
azure/rs_azure_networking/peering_test_cat.rb
azure/rs_azure_networking/rs_azure_networking_plugin.rb
azure/rs_azure_networking/vnet_dns_test_cat.rb
azure/rs_azure_networking/vnet_test_cat.rb

Added the network and subnet types to the rs_azure_networking plugin. Moved peering under rs_azure_networking.

Add Azure virtual network and subnet types

---

aws/rs_aws_rds/aws_rds_plugin.rb
aws/rs_aws_rds/changelog.md
libraries/plugin_generics.rb

fixes #112 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/113)

AWS RDS Plugin - updating to use generics, fix stop_debugging. 

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/114)

Week of 12-11-2017 release

---

azure/rs_azure_diagnostic_settings/README.md
azure/rs_azure_diagnostic_settings/changelog.md
azure/rs_azure_diagnostic_settings/diagnostic_settings_test_cat.rb
azure/rs_azure_diagnostic_settings/rs_azure_diagnostic_settings_plugin.rb
azure/rs_azure_key_vault/azure_keyvault_plugin.rb

Provides a plugin to interact with the Azure Service Diagnostic Settings resource.
N/A

Azure Service Diagnostic Settings plugin - Initial Release

---

README.md

Added Azure Service Diagnostic Settings to root readme
Missing link in root readme

Add Azure Service Diagnostic Settings to root readme

---

CHANGELOG.md

Week of 01-15-2018 Release

---

CHANGELOG.md

Release Week of 01/22/2018

---

aws/rs_aws_elb/README.md
aws/rs_aws_elb/aws_elb_plugin.rb
aws/rs_aws_elb/changelog.md

- adjust provision definition (#125)
- add show() action
- adjust register_instance() & deregister_instance() actions
#125

AWS ELB: Bug Fixes 

---

azure/rs_azure_mysql/azure_mysql_plugin.rb
azure/rs_azure_mysql/changelog.md

Adjust firewall_rules provision definition
#127

Azure MySQL: Firewall_Rules Provision() Bug Fix

---

CHANGELOG.md

Release Week of 01-29-2018

---

aws/rs_aws_alb/README.md
aws/rs_aws_cft/README.md
aws/rs_aws_efs/README.md
aws/rs_aws_elb/README.md
aws/rs_aws_rds/README.md
aws/rs_aws_vpc/README.md
azure/rs_azure_cache/README.md
azure/rs_azure_compute/README.md
azure/rs_azure_containerservices/README.md
azure/rs_azure_diagnostic_settings/README.md
azure/rs_azure_key_vault/README.md
azure/rs_azure_mysql/README.md
azure/rs_azure_networking/README.md
azure/rs_azure_pgsql/README.md
azure/rs_azure_sql/README.md
azure/rs_azure_storage/README.md
azure/rs_azure_template/README.md
fastly/ipaddresslist/README.md
google/gce/README.md
google/gce/examples/gce_external_network_lb/README.md
google/gce/examples/gce_internal_tcp_lb/README.md
google/gke/README.md
google/google_bigtable/README.md
google/google_cloud_dns/README.md
google/google_cloud_sql/README.md
infoblox/ipam/README.md
vmware/nsx/README.md

Fixes the broken sys_log references in the readme.md files
Broken sys_log links

Fix broken sys_log references

---

azure/rs_azure_storage/README.md
azure/rs_azure_storage/azure_storage_plugin.rb
azure/rs_azure_storage/changelog.md
azure/rs_azure_storage/storage_test_cat.rb

Adds the update(patch) action to the plugin. Also brings the API version up to 2017-06-01
n/a

Azure Storage Plugin: Adds the update(patch) action to the plugin.

---

CHANGELOG.md

Release Week of 02-05-2018

---

aws/rs_aws_elasticache/aws_elasticache_plugin.rb
aws/rs_aws_elasticache/changelog.md
aws/rs_aws_elasticache/elasticache_test_cat.rb

adding header for content_type=application/xml
#138 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/139)

PSASSET-800 - adding header for content_type=application/xml, fixes #138

---

libraries/sys_log.rb

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/rightscale-plugins/140)

Sys_log library: Adding in warning about CM Actor permissions being needed. 

---

CHANGELOG.md

Release Week of 02-12-2018

---

README.md
azure/rs_azure_resources/README.md
azure/rs_azure_resources/arm_resource_test_cat.rb
azure/rs_azure_resources/changelog.md
azure/rs_azure_resources/rs_azure_resource.rb

Plugin that interacts with the Azure Resource Management/Resources API.
https://docs.microsoft.com/en-us/rest/api/resources/resources
N/A

rs_azure_resource Plugin Initial Release

---

README.md
aws/rs_aws_iam/CHANGELOG.md
aws/rs_aws_iam/README.md
aws/rs_aws_iam/aws_iam_plugin.rb
aws/rs_aws_iam/iam_test_cat.rb

New Plugin for managing IAM
None

adding IAM plugin

---

azure/rs_azure_compute/README.md
azure/rs_azure_compute/azure_compute_plugin.rb
azure/rs_azure_compute/scaleset_test_cat.rb

adding in scale sets

---

azure/rs_azure_compute/README.md
azure/rs_azure_compute/azure_compute_plugin.rb
azure/rs_azure_compute/changelog.md

- Adjusting availability_set href_template
- Adding stop(), start(), list(), list_all(), and instance_view() methods to virtualmachine resource
N/A

rs_azure_compute: Add new methods for virtualmachine resource

---

README.md
azure/rs_azure_cosmosdb/README.md
azure/rs_azure_cosmosdb/azure_cosmosdb_plugin.rb
azure/rs_azure_cosmosdb/changelog.md
azure/rs_azure_cosmosdb/cosmosdb_test_cat.rb

Adds support for create, read, update, and delete of Azure Cosmos DB Accounts in Self Service.
N/A

Azure CosmosDB Plugin

---

README.md
digital_ocean/README.md
digital_ocean/changelog.md
digital_ocean/digital_ocean_test_cat.rb
digital_ocean/rs_do_plugin.rb

Digital Ocean Plugin - Initial Release

Digital Ocean - Initial Release

---

CHANGELOG.md

Release Week of 05-07-2018

---

aws/rs_aws_rds/aws_rds_plugin.rb

Removed an extra "]"
Fixes compilation error.
- [X ] All tests pass.

fixed typo - removed extra "]"

---

azure/rs_azure_key_vault/README.md
azure/rs_azure_key_vault/azure_keyvault_plugin.rb
azure/rs_azure_key_vault/changelog.md

Added the `listbyresourcegroup` action
N/A

Azure Key Vault: Added the `listbyresourcegroup` action

---

google/google_cloud_sql/CHANGELOG.md
google/google_cloud_sql/README.md
google/google_cloud_sql/cloud_sql_test_cat.rb
google/google_cloud_sql/google_cloud_sql.rb

Adding in backup_runs resource to Google CloudSQL Plugins

PSASSET-868 Adding in backup_runs resource to Google CloudSQL Plugins

---

README.md
aws/rs_aws_eks/README.md
aws/rs_aws_eks/aws_eks_plugin.rb
aws/rs_aws_eks/changelog.md
aws/rs_aws_eks/eks_test_cat.rb

AWS EKS - Initial Release

---

README.md
google/google_deployment_manager/README.md
google/google_deployment_manager/changelog.md
google/google_deployment_manager/gce_dm_plugin.rb
google/google_deployment_manager/gce_dm_test_cat.rb

Google Deployment Manager

---

azure/rs_azure_networking/README.md
azure/rs_azure_networking/changelog.md
azure/rs_azure_networking/ip_test_cat.rb
azure/rs_azure_networking/rs_azure_networking_plugin.rb

Azure Networking Plugin - Add Public IP Address

---

azure/rs_azure_networking/README.md
azure/rs_azure_networking/changelog.md
azure/rs_azure_networking/ip_test_cat.rb
azure/rs_azure_networking/lb_test_cat.rb
azure/rs_azure_networking/nsg_to_subnet_test_cat.rb
azure/rs_azure_networking/peering_test_cat.rb
azure/rs_azure_networking/rs_azure_networking_plugin.rb
azure/rs_azure_networking/s2svpn-test-cat.rb
azure/rs_azure_networking/vnet_dns_test_cat.rb

Azure Networking Plugin - Adding in Local Gateway, Virtual Network Gateway, Connections

---

.gitattributes
.gitignore
flexera-plugins.code-workspace

Git enhancements

---

.mdlrc
.travis.yml
CODEOWNERS
CONTRIBUTING.md
Dangerfile
Gemfile
Gemfile.lock

Add travis and danger

---

README.md
azure/rs_azure_databricks/README.md
azure/rs_azure_databricks/azure_databricks_plugin.rb
azure/rs_azure_databricks/changelog.md
azure/rs_azure_databricks/databricks_test_cat.rb

Initial Release of Azure Databricks plugin

Azure Databricks: Initial Release

---

.travis.yml

add global secure variables

---

google/google_cloud_storage/google_cloud_storage.rb

adding more objects

---

aws/rs_aws_compute/aws_compute_plugin.rb
aws/rs_aws_compute/compute_instance_test_cat.rb
aws/rs_aws_compute/compute_plugin_test_cat.rb

Updating for the removal of items

---

CODEOWNERS

This will allow services to review and merge PR's, without bugging phx

Adding services to codeowners

---

package-lock.json
package.json

Updating textlint

---

CODEOWNERS
azure/rs_azure_sql/azure_sql_plugin.rb
azure/rs_azure_sql/changelog.md
azure/rs_azure_sql/sql_test_cat.rb

Azure updates

---

aws/rs_aws_compute/aws_compute_plugin.rb
aws/rs_aws_compute/changelog.md
aws/rs_aws_compute/compute_instance_test_cat.rb

This adds support for copies into the aws plugin. 

SEG-695 Support Copies

---

azure/rs_azure_compute/azure_compute_plugin.rb
azure/rs_azure_compute/changelog.md

Azure Compute Updates from WW Customer One

---

aws/rs_aws_compute/aws_compute_plugin.rb
aws/rs_aws_compute/changelog.md

AWS Compute Updates for security groups, snapshots, etc

---

azure/rs_azure_sql/azure_sql_plugin.rb
azure/rs_azure_sql/changelog.md

Updating from service clients repo
